version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: pub
    directory: "/"
    versioning-strategy: increase # https://github.com/dependabot/dependabot-core/issues/6446
    schedule:
      interval: weekly